Lint and add error checking

diff --git a/bin/ruby_autocorrect b/bin/ruby_autocorrect
--- a/bin/ruby_autocorrect
+++ b/bin/ruby_autocorrect
@@ -1,8 +1,13 @@
 #!/bin/sh
 set -e
 
+test -x $(command -v rubocop) || (
+  echo "Can't find rubocop" >&2
+  exit 1
+)
+
 tmp=$(mktemp).rb
 cat >"$tmp"
-rubocop -f q -a "$tmp" >/dev/null 2>&1 || true
+rubocop -a "$tmp" >/dev/null 2>&1 || true
 cat "$tmp"
 rm -f "$tmp"
